export default [
  {
    id: 1,
    image: "swimmer.png",
    figure: "5.0",
    rating: "(6)",
    cardheading: "Life lessons with Katie Zaferes",
    cardparagraph: "From $136",
    alt: "swimming",
    location: "USA",
    openSpots: 0,
  },
  {
    id: 2,
    image: "wedding-photography 1.png",
    figure: "5.0",
    rating: "(30)",
    cardheading: "Learn wedding photography",
    cardparagraph: "From $125",
    alt: "wedding",
    location: "Australia",
    openSpots: 27,
  },
  {
    id: 3,
    image: "mountainbike.png",
    figure: "4.8",
    rating: "(2)",
    cardheading: "Group Mountain Biking",
    alt: "bicycle",
    location: "Brazil",
    openSpots: 3,
  },
];
